# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Srijit Seal
name: Srijit Seal
position: PhD Student, University of Cambridge and Visiting Scientist, Broad Institute of MIT and Harvard
email: seal@broad.mit.edu
description: >-
  I am a researcher in chemoinformatics, centered on using machine learning techniques, particularly modeling, and interpretation of the Cell Painting assay, to predict drug bioactivity, safety, and toxicity. 
  <br>
  I am currently based at [Broad Institute of MIT and Harvard](https://www.broadinstitute.org) where I am advised by
  [Anne Carpenter](https://www.broadinstitute.org/bios/anne-e-carpenter) and [Shantanu Singh](https://www.broadinstitute.org/bios/shantanu-singh). 
  <br>
  I am also a final year Ph.D. student at the  [University of Cambridge](https://https://www.cam.ac.uk/) where I am advised by
  [Andreas Bender](https://www.ch.cam.ac.uk/person/ab454)
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://srijitseal.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: srijitseal
github_username: srijitseal
google_scholar: 0WxbtaAAAAAJ
google_analytics: G-8Z8BB08Y56

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
